#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname hw2) (read-case-sensitive #t) (teachpacks ()) (htdp-settings #(#t constructor repeating-decimal #f #t none #f () #f)))
;; DO NOT REMOVE THIS IMPORT. It is needed for `provide` to be usable under
;; racket language subsets.
(require "./provide-hack.rkt")

(check-expect (plus 1 2) 3)
(check-expect (plus 3 4) (+ 3 4))
(define (plus a b)
    (+ a b)
)

(check-expect (minus 1 2) -1)
(check-expect (minus 5 5) 0)
(define (minus a b)
    (- (helper a) b)
)

(define (helper a)
    a
)

(define-struct thing [field1 field2])
(define THING1 (make-thing "field1" #false))
(check-expect (thing? THING1) #true)
(check-expect (thing-field1 THING1) "field1")

;; Replace this provide form with the code generated by running "racket public-symbols.rkt"
(provide
    plus
    minus
    (struct-out thing)
)
